(function (root, factory) {
	root.golbal = factory(root)
})(this,function (root) {
	function EditorModule(argument) {
		// body...
	}

	var w = root.innerWidth
	// console.log(w)
	function Golbal() {
		this.name = 'Hpp';
		this.headTop = '0px';
		this.headTopColor = '#000';
		this.headStyle = {
			
			bgColor: '#000',
			color: '#FFF',
			fontSize: '15px',
			title: {
				fontSize: '20px'
			}
		}

		this.init()
	}

	Golbal.prototype =  {
		constructor:Golbal,

		init: function () {
			this.setEditorData()
			this.whiteHeaderStyle()
			this.setHppEditorData()

			this._addAttr(this.editorData,'clipType','')
			this._addAttr(this.hpEditorData,'clipType','')
			this._addAttr(this.editorData,'focus',false)
			this._addAttr(this.hpEditorData,'focus',false)
		},

		whiteHeaderStyle:function () {
			this.head_style_white = {
				head_top: this.headTop,
				head_top_color: '#fff',
				bg_color: "#fff",
				color:'#000',
				font_size: this.headStyle.fontSize,
				title: {
					font_size: this.headStyle.title.fontSize
				}
			}
		},

		_addAttr: function (obj,name,value) {
			obj.editModules.forEach(function (module) {
				module.editors.forEach(function (eidtor) {
					if(eidtor.hasOwnProperty(name)){

					}else {
						eidtor[name] = value
					}
				})
			})
		},

		setEditorData: function () {
			this.editorData = {
				moduleIndex:-1,
				editorIndex: -1,
				editModules:[
						{
							editors:[
								{
									type: 'img',
									
									componentName: 'img-container',
									locked:false,
									src:'',
									top:0,
									left:0,
									width: '100%',
									height: 60,
									rotate:0,
									backgroundColor:'#ff5b83',
									borderColor:'transparent',
									borderWidth:0,
									borderStyle:'solid',
									borderRadiusWidth:30,
									fixed:false,
									borderTopLeftRadius_w:30,
									borderTopLeftRadius_h:30,
									borderTopRightRadius_w:30,
									borderTopRightRadius_h:30,
									borderBottomLeftRadius_w: 0,
									borderBottomLeftRadius_h: 0,
									borderBottomRightRadius_w:0,
									borderBottomRightRadius_h:0,
								},
								{
									type: 'text',
									fixed:false,
									componentName: 'text-container',
									content:'嗨披详情页',
									top:10,
									left:'30%',
									defaultWidth:'40%',
									width: '40%',
									defaultHeight:20,
									height: 20,
									lineHeight: 1,
									rotate:0,
									scaleX:1,
									scaleY:1,
									fontFamily: 'Microsoft YaHei',
									fontSize: 20,
									letterSpacing: 0,
									color: '#fff',
									textAlign: 'center',
									locked:false,
									webkitTextStrokeColor: 'transparent',
									webkitTextStrokeWidth: 1,
								},
								{
									type: 'text',
									fixed:false,
									componentName: 'text-container',
									content:'HIPI DETAIL',
									top:30,
									left:'30%',
									defaultWidth:'40%',
									width: '40%',
									defaultHeight:20,
									height: 20,
									lineHeight: 1,
									rotate:0,
									scaleX:1,
									scaleY:1,
									fontFamily: 'Microsoft YaHei',
									fontSize: 15,
									letterSpacing: 0,
									color: '#fff',
									textAlign: 'center',
									locked:false,
									webkitTextStrokeColor: 'transparent',
									webkitTextStrokeWidth: 1,
								},
							],
							width:'100%',
							height:60,
							type: 'module',
						},
						{
							editors:[
								{
									type: 'text',
									fixed:false,
									componentName: 'text-container',
									content:'嗨披详情页',
									top:10,
									left:'20%',
									defaultWidth:'60%',
									width: '60%',
									defaultHeight:40,
									height: 40,
									lineHeight: 1,
									rotate:0,
									scaleX:1,
									scaleY:1,
									fontFamily: 'Microsoft YaHei',
									fontSize: 40,
									letterSpacing: 0,
									color: '#000',
									textAlign: 'center',
									locked:false,
									webkitTextStrokeColor: 'transparent',
									webkitTextStrokeWidth: 1,
								},
								// {
								// 	type: 'img',
								// 	componentName: 'img-container',
								// 	locked:false,
								// 	src:'../../content/images/slide1.jpg',
								// 	top:30,
								// 	left:'2%',
								// 	width: '96%',
								// 	height: 400,
								// 	rotate:0,
								// 	borderRadiusWidth:0,

									
								// 	fixed:false,
								// 	borderTopLeftRadius_w:0,
								// 	borderTopLeftRadius_h:0,
								// 	borderTopRightRadius_w:0,
								// 	borderTopRightRadius_h:0,
								// 	borderBottomLeftRadius_w: 0,
								// 	borderBottomLeftRadius_h: 0,
								// 	borderBottomRightRadius_w:0,
								// 	borderBottomRightRadius_h:0,
								// 	backgroundColor:'transparent',
								// 	borderColor:'transparent',
								// 	borderWidth:0,
								// 	borderStyle:'solid',
								// 	// clipType:'clip1'
								// },
								{
									type: 'img',
									componentName: 'img-container',
									locked:false,
									src:'',
									top:150,
									left:'2%',
									width: '96%',
									height: 200,
									borderRadiusWidth:0,

									rotate:0,
									fixed:false,
									borderTopLeftRadius_w:0,
									borderTopLeftRadius_h:0,
									borderTopRightRadius_w:0,
									borderTopRightRadius_h:0,
									borderBottomLeftRadius_w: 0,
									borderBottomLeftRadius_h: 0,
									borderBottomRightRadius_w:0,
									borderBottomRightRadius_h:0,
									backgroundColor:'transparent',
									borderColor:'#ccc',
									borderWidth:1,
									borderStyle:'solid',
								}
							],
							type: 'module',
							left:0,
							bgc:'#fff',
							width:'100%',
							height:800
						}
					]
				}
		},

		setHppEditorData: function () {

			var data = this.hpEditorData = {
				moduleIndex:-1,
				editorIndex: -1,
				editModules:[
					{
						type: 'module',
						width:'100%',
						height:50,
						editors:[
							{
								type: 'img',
								componentName: 'img-container',
								locked:false,
								src:'',
								top:0,
								left:0,
								width: '100%',
								height: 50,
								borderRadiusWidth:0,

								rotate:0,
								fixed:true,
								borderTopLeftRadius_w:25,
								borderTopLeftRadius_h:25,
								borderTopRightRadius_w:25,
								borderTopRightRadius_h:25,
								borderBottomLeftRadius_w: 0,
								borderBottomLeftRadius_h: 0,
								borderBottomRightRadius_w:0,
								borderBottomRightRadius_h:0,
								backgroundColor:'#729415',
								borderColor:'#ccc',
								borderWidth:0,
								borderStyle:'solid',
							},
							{
								type: 'text',
								fixed:false,
								componentName: 'text-container',
								content:'嗨披详情页',
								top:10,
								left:'30%',
								defaultWidth:'40%',
								width: '40%',
								defaultHeight:17,
								height: 17,
								lineHeight:1.0,
								rotate:0,
								scaleX:1,
								scaleY:1,
								fontFamily: 'Microsoft YaHei',
								fontSize: 17,
								letterSpacing: 0,
								color: '#fff',
								textAlign: 'center',
								locked:false
							},
							{
								type: 'text',
								fixed:false,
								componentName: 'text-container',
								content:'HIPI DETAIL',
								top:30,
								left:'30%',
								width: '40%',
								height: 17,
								lineHeight:1.0,
								rotate:0,
								fontFamily: 'Microsoft YaHei',
								fontSize: 15,
								letterSpacing: 0,
								color: '#fff',
								textAlign: 'center',
								borderRadiusWidth:0,
								webkitTextStrokeColor: 'transparent',
								webkitTextStrokeWidth: 1,
								locked:false
							},
						]
					},
					{
						type: 'module',
						width:'100%',
						height:320,
						editors:[
							{
								type: 'img',
								componentName: 'img-container',
								locked:false,
								src:'',
								top:0,
								left:0,
								width: '100%',
								height: 320,
								borderRadiusWidth:0,

								rotate:0,
								fixed:true,
								borderTopLeftRadius_w:0,
								borderTopLeftRadius_h:0,
								borderTopRightRadius_w:0,
								borderTopRightRadius_h:0,
								borderBottomLeftRadius_w: 0,
								borderBottomLeftRadius_h: 0,
								borderBottomRightRadius_w:0,
								borderBottomRightRadius_h:0,
								backgroundColor:'transparent',
								borderColor:'#000',
								borderWidth:1,
								borderStyle:'solid',
							},
							{
								type: 'text',
								fixed:false,
								componentName: 'text-container',
								content:'HIPI DETAIL',
								top:30,
								left:'38%',
								width: '24%',
								height: 130,
								lineHeight:1.0,
								rotate:0,
								fontFamily: 'Microsoft YaHei',
								fontSize: 15,
								letterSpacing: 0,
								color: '#fff',
								textAlign: 'center',
								borderRadiusWidth:0,
								webkitTextStrokeColor: 'transparent',
								webkitTextStrokeWidth: 1,
								locked:false
							},
						]
					},
					{
						type: 'module',
						width:'100%',
						height:100,
						editors:[
							{

								type: 'img',
								componentName: 'img-container',
								locked:false,
								src:'',
								top:0,
								left:0,
								width: '100%',
								height: 100,
								borderRadiusWidth:0,

								rotate:0,
								fixed:true,
								borderTopLeftRadius_w:0,
								borderTopLeftRadius_h:0,
								borderTopRightRadius_w:0,
								borderTopRightRadius_h:0,
								borderBottomLeftRadius_w: 0,
								borderBottomLeftRadius_h: 0,
								borderBottomRightRadius_w:0,
								borderBottomRightRadius_h:0,
								backgroundColor:'#729415',
								borderColor:'',
								borderWidth:0,
								borderStyle:'solid'
							}
						]
					},
					{
						type: 'module',
						width:'100%',
						height:410,
						editors:[
							{

								type: 'img',
								componentName: 'img-container',
								locked:false,
								src:'',
								top:0,
								left:0,
								width: '100%',
								height: 410,
								borderRadiusWidth:0,

								rotate:0,
								fixed:true,
								borderTopLeftRadius_w:0,
								borderTopLeftRadius_h:0,
								borderTopRightRadius_w:0,
								borderTopRightRadius_h:0,
								borderBottomLeftRadius_w: 0,
								borderBottomLeftRadius_h: 0,
								borderBottomRightRadius_w:0,
								borderBottomRightRadius_h:0,
								backgroundColor:'#97b600',
								borderColor:'',
								borderWidth:0,
								borderStyle:'solid'
							},
							{
								type: 'text',
								fixed:false,
								componentName: 'text-container',
								content:'',
								top:25,
								left:'25%',
								width: '50%',
								height: 52,
								lineHeight:1.0,
								rotate:0,
								fontFamily: 'Microsoft YaHei',
								fontSize: 15,
								letterSpacing: 0,
								color: '#fff',
								textAlign: 'center',
								borderRadiusWidth:0,
								webkitTextStrokeColor: 'transparent',
								webkitTextStrokeWidth: 1,
								locked:false
							},
							{
								type: 'text',
								fixed:false,
								componentName: 'text-container',
								content:'',
								top:83,
								left:'16%',
								width: '68%',
								height: 29,
								lineHeight:1.0,
								rotate:0,
								fontFamily: 'Microsoft YaHei',
								fontSize: 15,
								letterSpacing: 0,
								color: '#fff',
								textAlign: 'center',
								borderRadiusWidth:0,
								webkitTextStrokeColor: 'transparent',
								webkitTextStrokeWidth: 1,
								locked:false
							},
							{
								type: 'text',
								fixed:false,
								componentName: 'text-container',
								content:'',
								top:117,
								left:'19%',
								width: '62%',
								height: 29,
								lineHeight:1.0,
								rotate:0,
								fontFamily: 'Microsoft YaHei',
								fontSize: 15,
								letterSpacing: 0,
								color: '#fff',
								textAlign: 'center',
								borderRadiusWidth:0,
								webkitTextStrokeColor: 'transparent',
								webkitTextStrokeWidth: 1,
								locked:false
							},
							{
								type: 'text',
								fixed:false,
								componentName: 'text-container',
								content:'',
								top:170,
								left:'59%',
								width: '36%',
								height: 220,
								lineHeight:1.0,
								rotate:0,
								fontFamily: 'Microsoft YaHei',
								fontSize: 15,
								letterSpacing: 0,
								color: '#fff',
								textAlign: 'center',
								borderRadiusWidth:0,
								webkitTextStrokeColor: 'transparent',
								webkitTextStrokeWidth: 1,
								locked:false
							},
							{

								type: 'img',
								componentName: 'img-container',
								locked:false,
								src:'',
								top:170,
								left:'7%',
								width: '48%',
								height: 220,
								borderRadiusWidth:0,

								rotate:0,
								fixed:true,
								borderTopLeftRadius_w:0,
								borderTopLeftRadius_h:0,
								borderTopRightRadius_w:0,
								borderTopRightRadius_h:0,
								borderBottomLeftRadius_w: 0,
								borderBottomLeftRadius_h: 0,
								borderBottomRightRadius_w:0,
								borderBottomRightRadius_h:0,
								backgroundColor:'transparent',
								borderColor:'',
								borderWidth:0,
								borderStyle:'solid'
							},
						]
					},
					{
						type: 'module',
						width:'100%',
						height:450,
						editors:[
							{

								type: 'img',
								componentName: 'img-container',
								locked:false,
								src:'',
								top:0,
								left:0,
								width: '100%',
								height: 450,
								borderRadiusWidth:0,

								rotate:0,
								fixed:true,
								borderTopLeftRadius_w:0,
								borderTopLeftRadius_h:0,
								borderTopRightRadius_w:0,
								borderTopRightRadius_h:0,
								borderBottomLeftRadius_w: 0,
								borderBottomLeftRadius_h: 0,
								borderBottomRightRadius_w:0,
								borderBottomRightRadius_h:0,
								backgroundColor:'transparent',
								borderColor:'#000',
								borderWidth:1,
								borderStyle:'solid'
							},
							{
								type: 'text',
								fixed:false,
								componentName: 'text-container',
								content:'',
								top:25,
								left:'25%',
								width: '50%',
								height: 52,
								lineHeight:1.0,
								rotate:0,
								fontFamily: 'Microsoft YaHei',
								fontSize: 15,
								letterSpacing: 0,
								color: '#fff',
								textAlign: 'center',
								borderRadiusWidth:0,
								webkitTextStrokeColor: 'transparent',
								webkitTextStrokeWidth: 1,
								locked:false
							},
							{
								type: 'text',
								fixed:false,
								componentName: 'text-container',
								content:'',
								top:83,
								left:'16%',
								width: '68%',
								height: 29,
								lineHeight:1.0,
								rotate:0,
								fontFamily: 'Microsoft YaHei',
								fontSize: 15,
								letterSpacing: 0,
								color: '#fff',
								textAlign: 'center',
								borderRadiusWidth:0,
								webkitTextStrokeColor: 'transparent',
								webkitTextStrokeWidth: 1,
								locked:false
							},
							{
								type: 'text',
								fixed:false,
								componentName: 'text-container',
								content:'',
								top:117,
								left:'19%',
								width: '62%',
								height: 29,
								lineHeight:1.0,
								rotate:0,
								fontFamily: 'Microsoft YaHei',
								fontSize: 15,
								letterSpacing: 0,
								color: '#fff',
								textAlign: 'center',
								borderRadiusWidth:0,
								webkitTextStrokeColor: 'transparent',
								webkitTextStrokeWidth: 1,
								locked:false
							}
						]
					},
					{
						type: 'module',
						width:'100%',
						height:310,
						editors:[
							{

								type: 'img',
								componentName: 'img-container',
								locked:false,
								src:'',
								top:0,
								left:0,
								width: '100%',
								height: 310,
								borderRadiusWidth:0,

								rotate:0,
								fixed:true,
								borderTopLeftRadius_w:0,
								borderTopLeftRadius_h:0,
								borderTopRightRadius_w:0,
								borderTopRightRadius_h:0,
								borderBottomLeftRadius_w: 0,
								borderBottomLeftRadius_h: 0,
								borderBottomRightRadius_w:0,
								borderBottomRightRadius_h:0,
								backgroundColor:'transparent',
								borderColor:'#000',
								borderWidth:1,
								borderStyle:'solid'
							},
							{
								type: 'text',
								fixed:false,
								componentName: 'text-container',
								content:'',
								top:25,
								left:'25%',
								width: '50%',
								height: 52,
								lineHeight:1.0,
								rotate:0,
								fontFamily: 'Microsoft YaHei',
								fontSize: 15,
								letterSpacing: 0,
								color: '#fff',
								textAlign: 'center',
								borderRadiusWidth:0,
								webkitTextStrokeColor: 'transparent',
								webkitTextStrokeWidth: 1,
								locked:false
							},
							{
								type: 'text',
								fixed:false,
								componentName: 'text-container',
								content:'',
								top:83,
								left:'16%',
								width: '68%',
								height: 29,
								lineHeight:1.0,
								rotate:0,
								fontFamily: 'Microsoft YaHei',
								fontSize: 15,
								letterSpacing: 0,
								color: '#fff',
								textAlign: 'center',
								borderRadiusWidth:0,
								webkitTextStrokeColor: 'transparent',
								webkitTextStrokeWidth: 1,
								locked:false
							},
							{
								type: 'text',
								fixed:false,
								componentName: 'text-container',
								content:'',
								top:117,
								left:'19%',
								width: '62%',
								height: 29,
								lineHeight:1.0,
								rotate:0,
								fontFamily: 'Microsoft YaHei',
								fontSize: 15,
								letterSpacing: 0,
								color: '#fff',
								textAlign: 'center',
								borderRadiusWidth:0,
								webkitTextStrokeColor: 'transparent',
								webkitTextStrokeWidth: 1,
								locked:false
							}
						]
					},
					{
						type: 'module',
						width:'100%',
						height:430 ,
						editors:[
							{

								type: 'img',
								componentName: 'img-container',
								locked:false,
								src:'',
								top: 145,
								left:(w - 230 ) / 2,
								width: 230,
								height: 230,
								borderRadiusWidth:0,

								rotate:0,
								fixed:true,
								borderTopLeftRadius_w:115,
								borderTopLeftRadius_h:115,
								borderTopRightRadius_w:115,
								borderTopRightRadius_h:115,
								borderBottomLeftRadius_w: 115,
								borderBottomLeftRadius_h: 115,
								borderBottomRightRadius_w:115,
								borderBottomRightRadius_h:115,
								backgroundColor:'transparent',
								borderColor:'#000',
								borderWidth:1,
								borderStyle:'solid'
							},

							{

								type: 'img',
								componentName: 'img-container',
								locked:false,
								src:'',
								top: 140,
								left: (w - 230 ) / 2 - 25,
								width: 88,
								height: 88,
								borderRadiusWidth:0,

								rotate:0,
								fixed:true,
								borderTopLeftRadius_w:44,
								borderTopLeftRadius_h:44,
								borderTopRightRadius_w:44,
								borderTopRightRadius_h:44,
								borderBottomLeftRadius_w: 44,
								borderBottomLeftRadius_h: 44,
								borderBottomRightRadius_w:44,
								borderBottomRightRadius_h:44,
								backgroundColor:'transparent',
								borderColor:'#000',
								borderWidth:1,
								borderStyle:'solid'
							},
							{

								type: 'img',
								componentName: 'img-container',
								locked:false,
								src:'',
								top: 114,
								left: (w - 230 ) / 2 + 159,
								width: 88,
								height: 88,
								borderRadiusWidth:0,

								rotate:0,
								fixed:true,
								borderTopLeftRadius_w:44,
								borderTopLeftRadius_h:44,
								borderTopRightRadius_w:44,
								borderTopRightRadius_h:44,
								borderBottomLeftRadius_w: 44,
								borderBottomLeftRadius_h: 44,
								borderBottomRightRadius_w:44,
								borderBottomRightRadius_h:44,
								backgroundColor:'transparent',
								borderColor:'#000',
								borderWidth:1,
								borderStyle:'solid'
							},
							{

								type: 'img',
								componentName: 'img-container',
								locked:false,
								src:'',
								top: 322 ,
								left: (w - 230 ) / 2 - 6,
								width: 88,
								height: 88,
								borderRadiusWidth:0,

								rotate:0,
								fixed:true,
								borderTopLeftRadius_w:44,
								borderTopLeftRadius_h:44,
								borderTopRightRadius_w:44,
								borderTopRightRadius_h:44,
								borderBottomLeftRadius_w: 44,
								borderBottomLeftRadius_h: 44,
								borderBottomRightRadius_w:44,
								borderBottomRightRadius_h:44,
								backgroundColor:'transparent',
								borderColor:'#000',
								borderWidth:1,
								borderStyle:'solid'
							},
							{

								type: 'img',
								componentName: 'img-container',
								locked:false,
								src:'',
								top: 302 ,
								left: (w - 230 ) / 2 + 164,
								width: 88,
								height: 88,
								borderRadiusWidth:0,

								rotate:0,
								fixed:true,
								borderTopLeftRadius_w:44,
								borderTopLeftRadius_h:44,
								borderTopRightRadius_w:44,
								borderTopRightRadius_h:44,
								borderBottomLeftRadius_w: 44,
								borderBottomLeftRadius_h: 44,
								borderBottomRightRadius_w:44,
								borderBottomRightRadius_h:44,
								backgroundColor:'transparent',
								borderColor:'#000',
								borderWidth:1,
								borderStyle:'solid'
							},
							{
								type: 'text',
								fixed:false,
								componentName: 'text-container',
								content:'',
								top:18,
								left:'25%',
								width: '50%',
								height: 52,
								lineHeight:1.0,
								rotate:0,
								fontFamily: 'Microsoft YaHei',
								fontSize: 15,
								letterSpacing: 0,
								color: '#fff',
								textAlign: 'center',
								borderRadiusWidth:0,
								webkitTextStrokeColor: 'transparent',
								webkitTextStrokeWidth: 1,
								locked:false
							},
							{
								type: 'text',
								fixed:false,
								componentName: 'text-container',
								content:'',
								top:76,
								left:'16%',
								width: '68%',
								height: 29,
								lineHeight:1.0,
								rotate:0,
								fontFamily: 'Microsoft YaHei',
								fontSize: 15,
								letterSpacing: 0,
								color: '#fff',
								textAlign: 'center',
								borderRadiusWidth:0,
								webkitTextStrokeColor: 'transparent',
								webkitTextStrokeWidth: 1,
								locked:false
							},
							{
								type: 'text',
								fixed:false,
								componentName: 'text-container',
								content:'',
								top:110,
								left:'19%',
								width: '62%',
								height: 29,
								lineHeight:1.0,
								rotate:0,
								fontFamily: 'Microsoft YaHei',
								fontSize: 15,
								letterSpacing: 0,
								color: '#fff',
								textAlign: 'center',
								borderRadiusWidth:0,
								webkitTextStrokeColor: 'transparent',
								webkitTextStrokeWidth: 1,
								locked:false
							}
						]
					},
					{
						height: 555,
						type: 'module',
						width:'100%',
						editors:[
							{
								type: 'img',
								componentName: 'img-container',
								locked:false,
								src:'',
								top: 0,
								left:0,
								width: w,
								height: 555,
								borderRadiusWidth:0,

								rotate:0,
								fixed:true,
								borderTopLeftRadius_w:0,
								borderTopLeftRadius_h:0,
								borderTopRightRadius_w:0,
								borderTopRightRadius_h:0,
								borderBottomLeftRadius_w: 0,
								borderBottomLeftRadius_h: 0,
								borderBottomRightRadius_w:0,
								borderBottomRightRadius_h:0,
								backgroundColor:'#97b600',
								borderColor:'',
								borderWidth:0,
								borderStyle:'solid'
							},
							{
								type: 'text',
								fixed:false,
								componentName: 'text-container',
								content:'',
								top:18,
								left:'25%',
								width: '50%',
								height: 40,
								lineHeight:1.0,
								rotate:0,
								fontFamily: 'Microsoft YaHei',
								fontSize: 15,
								letterSpacing: 0,
								color: '#fff',
								textAlign: 'center',
								borderRadiusWidth:0,
								webkitTextStrokeColor: 'transparent',
								webkitTextStrokeWidth: 1,
								locked:false
							},
							{
								type: 'text',
								fixed:false,
								componentName: 'text-container',
								content:'',
								top:66,
								left:'16%',
								width: '68%',
								height: 23,
								lineHeight:1.0,
								rotate:0,
								fontFamily: 'Microsoft YaHei',
								fontSize: 15,
								letterSpacing: 0,
								color: '#fff',
								textAlign: 'center',
								borderRadiusWidth:0,
								webkitTextStrokeColor: 'transparent',
								webkitTextStrokeWidth: 1,
								locked:false
							},
							{
								type: 'text',
								fixed:false,
								componentName: 'text-container',
								content:'',
								top:100,
								left:'19%',
								width: '62%',
								height: 23,
								lineHeight:1.0,
								rotate:0,
								fontFamily: 'Microsoft YaHei',
								fontSize: 15,
								letterSpacing: 0,
								color: '#fff',
								textAlign: 'center',
								borderRadiusWidth:0,
								webkitTextStrokeColor: 'transparent',
								webkitTextStrokeWidth: 1,
								locked:false
							},
							{
								type: 'img',
								componentName: 'img-container',
								locked:false,
								src:'',
								top: 130,
								left:20 * w / 375,
								width: 333 * w / 375,
								height: 136,
								borderRadiusWidth:0,

								rotate:0,
								fixed:true,
								borderTopLeftRadius_w:0,
								borderTopLeftRadius_h:0,
								borderTopRightRadius_w:0,
								borderTopRightRadius_h:0,
								borderBottomLeftRadius_w: 0,
								borderBottomLeftRadius_h: 0,
								borderBottomRightRadius_w:0,
								borderBottomRightRadius_h:0,
								backgroundColor:'',
								borderColor:'',
								borderWidth:0,
								borderStyle:'solid'
							},
							{
								type: 'img',
								componentName: 'img-container',
								locked:false,
								src:'',
								top: 270,
								left:20 * w / 375,
								width: 173 * w / 375,
								height: 160,
								borderRadiusWidth:0,

								rotate:0,
								fixed:true,
								borderTopLeftRadius_w:0,
								borderTopLeftRadius_h:0,
								borderTopRightRadius_w:0,
								borderTopRightRadius_h:0,
								borderBottomLeftRadius_w: 0,
								borderBottomLeftRadius_h: 0,
								borderBottomRightRadius_w:0,
								borderBottomRightRadius_h:0,
								backgroundColor:'',
								borderColor:'',
								borderWidth:0,
								borderStyle:'solid'
							},
							{
								type: 'img',
								componentName: 'img-container',
								locked:false,
								src:'',
								top: 270,
								left:200 * w / 375,
								width: 153 * w / 375,
								height: 80,
								borderRadiusWidth:0,

								rotate:0,
								fixed:true,
								borderTopLeftRadius_w:0,
								borderTopLeftRadius_h:0,
								borderTopRightRadius_w:0,
								borderTopRightRadius_h:0,
								borderBottomLeftRadius_w: 0,
								borderBottomLeftRadius_h: 0,
								borderBottomRightRadius_w:0,
								borderBottomRightRadius_h:0,
								backgroundColor:'',
								borderColor:'',
								borderWidth:0,
								borderStyle:'solid'
							},
							{
								type: 'img',
								componentName: 'img-container',
								locked:false,
								src:'',
								top: 350,
								left:200 * w / 375,
								width: 153 * w / 375,
								height: 80,
								borderRadiusWidth:0,

								rotate:0,
								fixed:true,
								borderTopLeftRadius_w:0,
								borderTopLeftRadius_h:0,
								borderTopRightRadius_w:0,
								borderTopRightRadius_h:0,
								borderBottomLeftRadius_w: 0,
								borderBottomLeftRadius_h: 0,
								borderBottomRightRadius_w:0,
								borderBottomRightRadius_h:0,
								backgroundColor:'',
								borderColor:'',
								borderWidth:0,
								borderStyle:'solid'
							},

							{
								type: 'img',
								componentName: 'img-container',
								locked:false,
								src:'',
								top: 440,
								left:20 * w / 375,
								width: 173 * w / 375,
								height: 40,
								borderRadiusWidth:0,

								rotate:0,
								fixed:true,
								borderTopLeftRadius_w:0,
								borderTopLeftRadius_h:0,
								borderTopRightRadius_w:0,
								borderTopRightRadius_h:0,
								borderBottomLeftRadius_w: 0,
								borderBottomLeftRadius_h: 0,
								borderBottomRightRadius_w:0,
								borderBottomRightRadius_h:0,
								backgroundColor:'',
								borderColor:'',
								borderWidth:0,
								borderStyle:'solid'
							},

							{
								type: 'img',
								componentName: 'img-container',
								locked:false,
								src:'',
								top: 440,
								left:200 * w / 375,
								width: 153 * w / 375,
								height: 40,
								borderRadiusWidth:0,

								rotate:0,
								fixed:true,
								borderTopLeftRadius_w:0,
								borderTopLeftRadius_h:0,
								borderTopRightRadius_w:0,
								borderTopRightRadius_h:0,
								borderBottomLeftRadius_w: 0,
								borderBottomLeftRadius_h: 0,
								borderBottomRightRadius_w:0,
								borderBottomRightRadius_h:0,
								backgroundColor:'',
								borderColor:'',
								borderWidth:0,
								borderStyle:'solid'
							},

							{
								type: 'img',
								componentName: 'img-container',
								locked:false,
								src:'',
								top: 490,
								left:20 * w / 375,
								width: 173 * w / 375,
								height: 40,
								borderRadiusWidth:0,

								rotate:0,
								fixed:true,
								borderTopLeftRadius_w:0,
								borderTopLeftRadius_h:0,
								borderTopRightRadius_w:0,
								borderTopRightRadius_h:0,
								borderBottomLeftRadius_w: 0,
								borderBottomLeftRadius_h: 0,
								borderBottomRightRadius_w:0,
								borderBottomRightRadius_h:0,
								backgroundColor:'',
								borderColor:'',
								borderWidth:0,
								borderStyle:'solid'
							},

							{
								type: 'img',
								componentName: 'img-container',
								locked:false,
								src:'',
								top: 490,
								left:200 * w / 375,
								width: 153 * w / 375,
								height: 40,
								borderRadiusWidth:0,

								rotate:0,
								fixed:true,
								borderTopLeftRadius_w:0,
								borderTopLeftRadius_h:0,
								borderTopRightRadius_w:0,
								borderTopRightRadius_h:0,
								borderBottomLeftRadius_w: 0,
								borderBottomLeftRadius_h: 0,
								borderBottomRightRadius_w:0,
								borderBottomRightRadius_h:0,
								backgroundColor:'',
								borderColor:'',
								borderWidth:0,
								borderStyle:'solid'
							},


						]
					},
					{
						height: 300,
						type: 'module',
						width:'100%',
						editors:[
							{
								type: 'img',
								componentName: 'img-container',
								locked:false,
								src:'',
								top: 0,
								left:0,
								width: w,
								height: 300,
								borderRadiusWidth:0,

								rotate:0,
								fixed:true,
								borderTopLeftRadius_w:0,
								borderTopLeftRadius_h:0,
								borderTopRightRadius_w:0,
								borderTopRightRadius_h:0,
								borderBottomLeftRadius_w: 0,
								borderBottomLeftRadius_h: 0,
								borderBottomRightRadius_w:0,
								borderBottomRightRadius_h:0,
								backgroundColor:'transparent',
								borderColor:'',
								borderWidth:0,
								borderStyle:'solid'
							},
						]
					},
					{
						height: 650,
						type: 'module',
						width:'100%',
						editors:[
							{
								type: 'img',
								componentName: 'img-container',
								locked:false,
								src:'',
								top: 0,
								left:0,
								width: w,
								height: 650,
								borderRadiusWidth:0,

								rotate:0,
								fixed:true,
								borderTopLeftRadius_w:0,
								borderTopLeftRadius_h:0,
								borderTopRightRadius_w:0,
								borderTopRightRadius_h:0,
								borderBottomLeftRadius_w: 0,
								borderBottomLeftRadius_h: 0,
								borderBottomRightRadius_w:0,
								borderBottomRightRadius_h:0,
								backgroundColor:'#97b600',
								borderColor:'',
								borderWidth:0,
								borderStyle:'solid'
							},
							{
								type: 'text',
								fixed:false,
								componentName: 'text-container',
								content:'',
								top:17,
								left:'25%',
								width: '50%',
								height: 32,
								lineHeight:1.0,
								rotate:0,
								fontFamily: 'Microsoft YaHei',
								fontSize: 15,
								letterSpacing: 0,
								color: '#fff',
								textAlign: 'center',
								borderRadiusWidth:0,
								webkitTextStrokeColor: 'transparent',
								webkitTextStrokeWidth: 1,
								locked:false
							},
							{
								type: 'text',
								fixed:false,
								componentName: 'text-container',
								content:'',
								top:52,
								left:'16%',
								width: '68%',
								height: 17,
								lineHeight:1.0,
								rotate:0,
								fontFamily: 'Microsoft YaHei',
								fontSize: 15,
								letterSpacing: 0,
								color: '#fff',
								textAlign: 'center',
								borderRadiusWidth:0,
								webkitTextStrokeColor: 'transparent',
								webkitTextStrokeWidth: 1,
								locked:false
							},
							{
								type: 'text',
								fixed:false,
								componentName: 'text-container',
								content:'',
								top:73,
								left:'19%',
								width: '62%',
								height: 17,
								lineHeight:1.0,
								rotate:0,
								fontFamily: 'Microsoft YaHei',
								fontSize: 15,
								letterSpacing: 0,
								color: '#fff',
								textAlign: 'center',
								borderRadiusWidth:0,
								webkitTextStrokeColor: 'transparent',
								webkitTextStrokeWidth: 1,
								locked:false
							},
							{
								type: 'img',
								componentName: 'img-container',
								locked:false,
								src:'',
								top: 143,
								left:72.5 * w / 375,
								width: 230,
								height: 230,
								borderRadiusWidth:0,

								rotate:0,
								fixed:true,
								borderTopLeftRadius_w:115,
								borderTopLeftRadius_h:115,
								borderTopRightRadius_w:115,
								borderTopRightRadius_h:115,
								borderBottomLeftRadius_w: 115,
								borderBottomLeftRadius_h: 115,
								borderBottomRightRadius_w:115,
								borderBottomRightRadius_h:115,
								backgroundColor:'#97b600',
								borderColor:'#fff',
								borderWidth:2,
								borderStyle:'solid'
							},
							{
								type: 'img',
								componentName: 'img-container',
								locked:false,
								src:'',
								top: 105,
								left:145 * w / 375,
								width: 86,
								height: 86,
								borderRadiusWidth:0,

								rotate:0,
								fixed:true,
								borderTopLeftRadius_w:43,
								borderTopLeftRadius_h:43,
								borderTopRightRadius_w:43,
								borderTopRightRadius_h:43,
								borderBottomLeftRadius_w: 43,
								borderBottomLeftRadius_h: 43,
								borderBottomRightRadius_w:43,
								borderBottomRightRadius_h:43,
								backgroundColor:'',
								borderColor:'#000',
								borderWidth:1,
								borderStyle:'solid'
							},
							{
								type: 'img',
								componentName: 'img-container',
								locked:false,
								src:'',
								top: 203,
								left:35 * w / 375,
								width: 86,
								height: 86,
								borderRadiusWidth:0,

								rotate:0,
								fixed:true,
								borderTopLeftRadius_w:43,
								borderTopLeftRadius_h:43,
								borderTopRightRadius_w:43,
								borderTopRightRadius_h:43,
								borderBottomLeftRadius_w: 43,
								borderBottomLeftRadius_h: 43,
								borderBottomRightRadius_w:43,
								borderBottomRightRadius_h:43,
								backgroundColor:'',
								borderColor:'#000',
								borderWidth:1,
								borderStyle:'solid'
							},
							{
								type: 'img',
								componentName: 'img-container',
								locked:false,
								src:'',
								top: 320,
								left:145 * w / 375,
								width: 86,
								height: 86,
								borderRadiusWidth:0,

								rotate:0,
								fixed:true,
								borderTopLeftRadius_w:43,
								borderTopLeftRadius_h:43,
								borderTopRightRadius_w:43,
								borderTopRightRadius_h:43,
								borderBottomLeftRadius_w: 43,
								borderBottomLeftRadius_h: 43,
								borderBottomRightRadius_w:43,
								borderBottomRightRadius_h:43,
								backgroundColor:'',
								borderColor:'#000',
								borderWidth:1,
								borderStyle:'solid'
							},

							{
								type: 'img',
								componentName: 'img-container',
								locked:false,
								src:'',
								top: 203,
								left:256 * w / 375,
								width: 86,
								height: 86,
								borderRadiusWidth:0,

								rotate:0,
								fixed:true,
								borderTopLeftRadius_w:43,
								borderTopLeftRadius_h:43,
								borderTopRightRadius_w:43,
								borderTopRightRadius_h:43,
								borderBottomLeftRadius_w: 43,
								borderBottomLeftRadius_h: 43,
								borderBottomRightRadius_w:43,
								borderBottomRightRadius_h:43,
								backgroundColor:'',
								borderColor:'#000',
								borderWidth:1,
								borderStyle:'solid'
							},

							{
								type: 'img',
								componentName: 'img-container',
								locked:false,
								src:'',
								top: 426,
								left:46 * w / 375,
								width: 134 * w / 375,
								height: 71,
								borderRadiusWidth:0,

								rotate:0,
								fixed:true,
								borderTopLeftRadius_w:0,
								borderTopLeftRadius_h:0,
								borderTopRightRadius_w:0,
								borderTopRightRadius_h:0,
								borderBottomLeftRadius_w: 0,
								borderBottomLeftRadius_h: 0,
								borderBottomRightRadius_w:0,
								borderBottomRightRadius_h:0,
								backgroundColor:'',
								borderColor:'',
								borderWidth:0,
								borderStyle:'solid'
							},

							{
								type: 'text',
								fixed:false,
								componentName: 'text-container',
								content:'',
								top:611,
								left: 46 * w / 375,
								width: 134 * w / 375,
								height: 17,
								lineHeight:1.0,
								rotate:0,
								fontFamily: 'Microsoft YaHei',
								fontSize: 15,
								letterSpacing: 0,
								color: '#fff',
								textAlign: 'center',
								borderRadiusWidth:0,
								webkitTextStrokeColor: 'transparent',
								webkitTextStrokeWidth: 1,
								locked:false
							},

							{
								type: 'img',
								componentName: 'img-container',
								locked:false,
								src:'',
								top: 426,
								left:198 * w / 375,
								width: 134 * w / 375,
								height: 71,
								borderRadiusWidth:0,

								rotate:0,
								fixed:true,
								borderTopLeftRadius_w:0,
								borderTopLeftRadius_h:0,
								borderTopRightRadius_w:0,
								borderTopRightRadius_h:0,
								borderBottomLeftRadius_w: 0,
								borderBottomLeftRadius_h: 0,
								borderBottomRightRadius_w:0,
								borderBottomRightRadius_h:0,
								backgroundColor:'',
								borderColor:'',
								borderWidth:0,
								borderStyle:'solid'
							},

							{
								type: 'text',
								fixed:false,
								componentName: 'text-container',
								content:'',
								top:502,
								left: 198 * w / 375,
								width: 134 * w / 375,
								height: 17,
								lineHeight:1.0,
								rotate:0,
								fontFamily: 'Microsoft YaHei',
								fontSize: 15,
								letterSpacing: 0,
								color: '#fff',
								textAlign: 'center',
								borderRadiusWidth:0,
								webkitTextStrokeColor: 'transparent',
								webkitTextStrokeWidth: 1,
								locked:false
							},

							{
								type: 'img',
								componentName: 'img-container',
								locked:false,
								src:'',
								top: 525,
								left:'6',
								width: '88%',
								height: 2,
								borderRadiusWidth:0,

								rotate:0,
								fixed:true,
								borderTopLeftRadius_w:0,
								borderTopLeftRadius_h:0,
								borderTopRightRadius_w:0,
								borderTopRightRadius_h:0,
								borderBottomLeftRadius_w: 0,
								borderBottomLeftRadius_h: 0,
								borderBottomRightRadius_w:0,
								borderBottomRightRadius_h:0,
								backgroundColor:'#708204',
								borderColor:'',
								borderWidth:0,
								borderStyle:'solid'
							},

							{
								type: 'img',
								componentName: 'img-container',
								locked:false,
								src:'',
								top: 535,
								left:46 * w / 375,
								width: 134 * w / 375,
								height: 71,
								borderRadiusWidth:0,

								rotate:0,
								fixed:true,
								borderTopLeftRadius_w:0,
								borderTopLeftRadius_h:0,
								borderTopRightRadius_w:0,
								borderTopRightRadius_h:0,
								borderBottomLeftRadius_w: 0,
								borderBottomLeftRadius_h: 0,
								borderBottomRightRadius_w:0,
								borderBottomRightRadius_h:0,
								backgroundColor:'',
								borderColor:'',
								borderWidth:0,
								borderStyle:'solid'
							},

							{
								type: 'text',
								fixed:false,
								componentName: 'text-container',
								content:'',
								top:502,
								left: 46 * w / 375,
								width: 134 * w / 375,
								height: 17,
								lineHeight:1.0,
								rotate:0,
								fontFamily: 'Microsoft YaHei',
								fontSize: 15,
								letterSpacing: 0,
								color: '#fff',
								textAlign: 'center',
								borderRadiusWidth:0,
								webkitTextStrokeColor: 'transparent',
								webkitTextStrokeWidth: 1,
								locked:false
							},

							{
								type: 'img',
								componentName: 'img-container',
								locked:false,
								src:'',
								top: 535,
								left:198 * w / 375,
								width: 134 * w / 375,
								height: 71,
								borderRadiusWidth:0,

								rotate:0,
								fixed:true,
								borderTopLeftRadius_w:0,
								borderTopLeftRadius_h:0,
								borderTopRightRadius_w:0,
								borderTopRightRadius_h:0,
								borderBottomLeftRadius_w: 0,
								borderBottomLeftRadius_h: 0,
								borderBottomRightRadius_w:0,
								borderBottomRightRadius_h:0,
								backgroundColor:'',
								borderColor:'',
								borderWidth:0,
								borderStyle:'solid'
							},

							{
								type: 'text',
								fixed:false,
								componentName: 'text-container',
								content:'',
								top:611,
								left: 198 * w / 375,
								width: 134 * w / 375,
								height: 17,
								lineHeight:1.0,
								rotate:0,
								fontFamily: 'Microsoft YaHei',
								fontSize: 15,
								letterSpacing: 0,
								color: '#fff',
								textAlign: 'center',
								borderRadiusWidth:0,
								webkitTextStrokeColor: 'transparent',
								webkitTextStrokeWidth: 1,
								locked:false
							},




						]
					},
					{
						height: 90,
						type: 'module',
						width:'100%',
						editors:[{
							type: 'text',
							fixed:false,
							componentName: 'text-container',
							content:'',
							top:19,
							left: 121 * w / 375,
							width: 137 * w / 375,
							height: 32,
							lineHeight:1.0,
							rotate:0,
							fontFamily: 'Microsoft YaHei',
							fontSize: 15,
							letterSpacing: 0,
							color: '#000',
							textAlign: 'center',
							borderRadiusWidth:0,
							webkitTextStrokeColor: 'transparent',
							webkitTextStrokeWidth: 1,
							locked:false
						},{
							type: 'text',
							fixed:false,
							componentName: 'text-container',
							content:'',
							top:54,
							left: 93 * w / 375,
							width: 191 * w / 375,
							height: 19,
							lineHeight:1.0,
							rotate:0,
							fontFamily: 'Microsoft YaHei',
							fontSize: 15,
							letterSpacing: 0,
							color: '#000',
							textAlign: 'center',
							borderRadiusWidth:0,
							webkitTextStrokeColor: 'transparent',
							webkitTextStrokeWidth: 1,
							locked:false
						}]
					},
					{
						height: 388,
						type: 'module',
						width:'100%',
						editors:[{
							type: 'img',
							componentName: 'img-container',
							locked:false,
							src:'',
							top: 0,
							left:0,
							width: w,
							height: 388,
							borderRadiusWidth:0,

							rotate:0,
							fixed:true,
							borderTopLeftRadius_w:0,
							borderTopLeftRadius_h:0,
							borderTopRightRadius_w:0,
							borderTopRightRadius_h:0,
							borderBottomLeftRadius_w: 0,
							borderBottomLeftRadius_h: 0,
							borderBottomRightRadius_w:0,
							borderBottomRightRadius_h:0,
							backgroundColor:'#97b600',
							borderColor:'#000',
							borderWidth:0,
							borderStyle:'solid'
						},{
							type: 'img',
							componentName: 'img-container',
							locked:false,
							src:'',
							top: 17,
							left: 45 * w / 375,
							width: 135 * w / 375,
							height: 132,
							borderRadiusWidth:0,

							rotate:0,
							fixed:true,
							borderTopLeftRadius_w:0,
							borderTopLeftRadius_h:0,
							borderTopRightRadius_w:0,
							borderTopRightRadius_h:0,
							borderBottomLeftRadius_w: 0,
							borderBottomLeftRadius_h: 0,
							borderBottomRightRadius_w:0,
							borderBottomRightRadius_h:0,
							backgroundColor:'transparent',
							borderColor:'#000',
							borderWidth:0,
							borderStyle:'solid'
						},{
							type: 'img',
							componentName: 'img-container',
							locked:false,
							src:'',
							top: 17,
							left: 198 * w / 375,
							width: 135 * w / 375,
							height: 132,
							borderRadiusWidth:0,

							rotate:0,
							fixed:true,
							borderTopLeftRadius_w:0,
							borderTopLeftRadius_h:0,
							borderTopRightRadius_w:0,
							borderTopRightRadius_h:0,
							borderBottomLeftRadius_w: 0,
							borderBottomLeftRadius_h: 0,
							borderBottomRightRadius_w:0,
							borderBottomRightRadius_h:0,
							backgroundColor:'transparent',
							borderColor:'#000',
							borderWidth:0,
							borderStyle:'solid'
						},{
							type: 'text',
							fixed:false,
							componentName: 'text-container',
							content:'',
							top:154,
							left: 45 * w / 375,
							width: 135 * w / 375,
							height: 23,
							lineHeight:1.0,
							rotate:0,
							fontFamily: 'Microsoft YaHei',
							fontSize: 15,
							letterSpacing: 0,
							color: '#000',
							textAlign: 'center',
							borderRadiusWidth:0,
							webkitTextStrokeColor: 'transparent',
							webkitTextStrokeWidth: 1,
							locked:false
						},{
							type: 'text',
							fixed:false,
							componentName: 'text-container',
							content:'',
							top:154,
							left: 198 * w / 375,
							width: 135 * w / 375,
							height: 23,
							lineHeight:1.0,
							rotate:0,
							fontFamily: 'Microsoft YaHei',
							fontSize: 15,
							letterSpacing: 0,
							color: '#000',
							textAlign: 'center',
							borderRadiusWidth:0,
							webkitTextStrokeColor: 'transparent',
							webkitTextStrokeWidth: 1,
							locked:false
						},{
							type: 'text',
							fixed:false,
							componentName: 'text-container',
							content:'',
							top:180,
							left: 45 * w / 375,
							width: 135 * w / 375,
							height: 13,
							lineHeight:1.0,
							rotate:0,
							fontFamily: 'Microsoft YaHei',
							fontSize: 12,
							letterSpacing: 0,
							color: '#000',
							textAlign: 'center',
							borderRadiusWidth:0,
							webkitTextStrokeColor: 'transparent',
							webkitTextStrokeWidth: 1,
							locked:false
						},{
							type: 'text',
							fixed:false,
							componentName: 'text-container',
							content:'',
							top:180,
							left: 198 * w / 375,
							width: 135 * w / 375,
							height: 13,
							lineHeight:1.0,
							rotate:0,
							fontFamily: 'Microsoft YaHei',
							fontSize: 12,
							letterSpacing: 0,
							color: '#000',
							textAlign: 'center',
							borderRadiusWidth:0,
							webkitTextStrokeColor: 'transparent',
							webkitTextStrokeWidth: 1,
							locked:false
						},{
							type: 'img',
							componentName: 'img-container',
							locked:false,
							src:'',
							top: 198,
							left: 45 * w / 375,
							width: 135 * w / 375,
							height: 132,
							borderRadiusWidth:0,

							rotate:0,
							fixed:true,
							borderTopLeftRadius_w:0,
							borderTopLeftRadius_h:0,
							borderTopRightRadius_w:0,
							borderTopRightRadius_h:0,
							borderBottomLeftRadius_w: 0,
							borderBottomLeftRadius_h: 0,
							borderBottomRightRadius_w:0,
							borderBottomRightRadius_h:0,
							backgroundColor:'transparent',
							borderColor:'#000',
							borderWidth:0,
							borderStyle:'solid'
						},{
							type: 'img',
							componentName: 'img-container',
							locked:false,
							src:'',
							top: 198,
							left: 198 * w / 375,
							width: 135 * w / 375,
							height: 132,
							borderRadiusWidth:0,

							rotate:0,
							fixed:true,
							borderTopLeftRadius_w:0,
							borderTopLeftRadius_h:0,
							borderTopRightRadius_w:0,
							borderTopRightRadius_h:0,
							borderBottomLeftRadius_w: 0,
							borderBottomLeftRadius_h: 0,
							borderBottomRightRadius_w:0,
							borderBottomRightRadius_h:0,
							backgroundColor:'transparent',
							borderColor:'#000',
							borderWidth:0,
							borderStyle:'solid'
						},{
							type: 'text',
							fixed:false,
							componentName: 'text-container',
							content:'',
							top:335,
							left: 45 * w / 375,
							width: 135 * w / 375,
							height: 23,
							lineHeight:1.0,
							rotate:0,
							fontFamily: 'Microsoft YaHei',
							fontSize: 15,
							letterSpacing: 0,
							color: '#000',
							textAlign: 'center',
							borderRadiusWidth:0,
							webkitTextStrokeColor: 'transparent',
							webkitTextStrokeWidth: 1,
							locked:false
						},{
							type: 'text',
							fixed:false,
							componentName: 'text-container',
							content:'',
							top:335,
							left: 198 * w / 375,
							width: 135 * w / 375,
							height: 23,
							lineHeight:1.0,
							rotate:0,
							fontFamily: 'Microsoft YaHei',
							fontSize: 15,
							letterSpacing: 0,
							color: '#000',
							textAlign: 'center',
							borderRadiusWidth:0,
							webkitTextStrokeColor: 'transparent',
							webkitTextStrokeWidth: 1,
							locked:false
						},{
							type: 'text',
							fixed:false,
							componentName: 'text-container',
							content:'',
							top:361,
							left: 45 * w / 375,
							width: 135 * w / 375,
							height: 13,
							lineHeight:1.0,
							rotate:0,
							fontFamily: 'Microsoft YaHei',
							fontSize: 12,
							letterSpacing: 0,
							color: '#000',
							textAlign: 'center',
							borderRadiusWidth:0,
							webkitTextStrokeColor: 'transparent',
							webkitTextStrokeWidth: 1,
							locked:false
						},{
							type: 'text',
							fixed:false,
							componentName: 'text-container',
							content:'',
							top:361,
							left: 198 * w / 375,
							width: 135 * w / 375,
							height: 13,
							lineHeight:1.0,
							rotate:0,
							fontFamily: 'Microsoft YaHei',
							fontSize: 12,
							letterSpacing: 0,
							color: '#000',
							textAlign: 'center',
							borderRadiusWidth:0,
							webkitTextStrokeColor: 'transparent',
							webkitTextStrokeWidth: 1,
							locked:false
						}]
					},{
						height: 42,
						type: 'module',
						width:'100%',
						editors: [
							{
								type: 'text',
								fixed:false,
								componentName: 'text-container',
								content:'',
								top:7,
								left: 136 * w / 375,
								width: 103 * w / 375,
								height: 18,
								lineHeight:1.0,
								rotate:0,
								fontFamily: 'Microsoft YaHei',
								fontSize: 12,
								letterSpacing: 0,
								color: '#000',
								textAlign: 'center',
								borderRadiusWidth:0,
								webkitTextStrokeColor: 'transparent',
								webkitTextStrokeWidth: 1,
								locked:false
							},
							{
								type: 'text',
								fixed:false,
								componentName: 'text-container',
								content:'',
								top:27,
								left: 136 * w / 375,
								width: 103 * w / 375,
								height: 10,
								lineHeight:1.0,
								rotate:0,
								fontFamily: 'Microsoft YaHei',
								fontSize: 12,
								letterSpacing: 0,
								color: '#000',
								textAlign: 'center',
								borderRadiusWidth:0,
								webkitTextStrokeColor: 'transparent',
								webkitTextStrokeWidth: 1,
								locked:false
							}
						]
					},{
						type: 'module',
						width:'100%',
						height:64,
						editors:[
							{
								type: 'img',
								componentName: 'img-container',
								locked:false,
								src:'../../content/images/editor/fuwu.jpg',
								top:0,
								left:0,
								width: '100%',
								height: 64,
								borderRadiusWidth:0,

								rotate:0,
								fixed:true,
								borderTopLeftRadius_w:0,
								borderTopLeftRadius_h:0,
								borderTopRightRadius_w:0,
								borderTopRightRadius_h:0,
								borderBottomLeftRadius_w: 0,
								borderBottomLeftRadius_h: 0,
								borderBottomRightRadius_w:0,
								borderBottomRightRadius_h:0,
								backgroundColor:'#fff',
								borderColor:'#ccc',
								borderWidth:1,
								borderStyle:'solid',
							}
						]
					},{
						type: 'module',
						width:'100%',
						height:160,
						editors:[
							{
								type: 'text',
								fixed:false,
								componentName: 'text-container',
								content:'',
								top:10,
								left:24 * w/375,
								width: 157 * w/375,
								height: 57,
								lineHeight:1.0,
								rotate:0,
								fontFamily: 'Microsoft YaHei',
								fontSize: 17,
								letterSpacing: 0,
								color: '#fff',
								textAlign: 'center',
								borderRadiusWidth:0,
								webkitTextStrokeColor: 'transparent',
								webkitTextStrokeWidth: 1,
								locked:false
							},
							{
								type: 'text',
								fixed:false,
								componentName: 'text-container',
								content:'',
								top:72,
								left:24 * w/375,
								width: 157 * w/375,
								height: 57,
								lineHeight:1.0,
								rotate:0,
								fontFamily: 'Microsoft YaHei',
								fontSize: 17,
								letterSpacing: 0,
								color: '#fff',
								textAlign: 'center',
								borderRadiusWidth:0,
								webkitTextStrokeColor: 'transparent',
								webkitTextStrokeWidth: 1,
								locked:false
							},
							{
								type: 'text',
								fixed:false,
								componentName: 'text-container',
								content:'',
								top:10,
								left:187 * w/375,
								width: 166 * w/375,
								height: 119,
								lineHeight:1.0,
								rotate:0,
								fontFamily: 'Microsoft YaHei',
								fontSize: 17,
								letterSpacing: 0,
								color: '#fff',
								textAlign: 'center',
								borderRadiusWidth:0,
								webkitTextStrokeColor: 'transparent',
								webkitTextStrokeWidth: 1,
								locked:false
							},
						]
					},{
						type: 'module',
						width:'100%',
						height:50,
						editors:[
							{
								type: 'img',
								componentName: 'img-container',
								locked:false,
								src:'',
								top:0,
								left:0,
								width: '100%',
								height: 50,
								borderRadiusWidth:0,

								rotate:0,
								fixed:true,
								borderTopLeftRadius_w:0,
								borderTopLeftRadius_h:0,
								borderTopRightRadius_w:0,
								borderTopRightRadius_h:0,
								borderBottomLeftRadius_w: 25,
								borderBottomLeftRadius_h: 25,
								borderBottomRightRadius_w:25,
								borderBottomRightRadius_h:25,
								backgroundColor:'#729415',
								borderColor:'#ccc',
								borderWidth:0,
								borderStyle:'solid',
							},
							{
								type: 'text',
								fixed:false,
								componentName: 'text-container',
								content:'嗨披详情页',
								top:10,
								left:'30%',
								width: '40%',
								height: 17,
								lineHeight:1.0,
								rotate:0,
								fontFamily: 'Microsoft YaHei',
								fontSize: 17,
								letterSpacing: 0,
								color: '#fff',
								textAlign: 'center',
								borderRadiusWidth:0,
								webkitTextStrokeColor: 'transparent',
								webkitTextStrokeWidth: 1,
								locked:false
							},
							{
								type: 'text',
								fixed:false,
								componentName: 'text-container',
								content:'HIPI DETAIL',
								top:30,
								left:'30%',
								width: '40%',
								height: 17,
								lineHeight:1.0,
								rotate:0,
								fontFamily: 'Microsoft YaHei',
								fontSize: 15,
								letterSpacing: 0,
								color: '#fff',
								textAlign: 'center',
								borderRadiusWidth:0,
								webkitTextStrokeColor: 'transparent',
								webkitTextStrokeWidth: 1,
								locked:false
							},
						]
					},
				]
			}
			

			data.editModules.forEach(function (module) {
				module.editors.forEach(function (editor) {
					if(editor.type == 'text'){
						editor.scaleX = 1;
						editor.scaleY = 1;
						editor.defaultWidth = editor.width;
						editor.defaultHeight = editor.height;
						var left = parseInt(editor.left)
						var width = parseInt(editor.width)
						if(left != (100 - width)/2){
							editor.textAlign = '';
						}
					}
					
				})
			})
		}	
	};


	return new Golbal()
})